// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: newsletterpb/v1/api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNewsLetterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body  string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *CreateNewsLetterRequest) Reset() {
	*x = CreateNewsLetterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newsletterpb_v1_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNewsLetterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewsLetterRequest) ProtoMessage() {}

func (x *CreateNewsLetterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newsletterpb_v1_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewsLetterRequest.ProtoReflect.Descriptor instead.
func (*CreateNewsLetterRequest) Descriptor() ([]byte, []int) {
	return file_newsletterpb_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewsLetterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNewsLetterRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type NewsLetter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewsLetterId string `protobuf:"bytes,1,opt,name=news_letter_id,json=newsLetterId,proto3" json:"news_letter_id,omitempty"`
	Title        string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body         string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *NewsLetter) Reset() {
	*x = NewsLetter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newsletterpb_v1_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsLetter) ProtoMessage() {}

func (x *NewsLetter) ProtoReflect() protoreflect.Message {
	mi := &file_newsletterpb_v1_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsLetter.ProtoReflect.Descriptor instead.
func (*NewsLetter) Descriptor() ([]byte, []int) {
	return file_newsletterpb_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *NewsLetter) GetNewsLetterId() string {
	if x != nil {
		return x.NewsLetterId
	}
	return ""
}

func (x *NewsLetter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NewsLetter) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type NewsScheme struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewsLetterId string `protobuf:"bytes,2,opt,name=news_letter_id,json=newsLetterId,proto3" json:"news_letter_id,omitempty"`
	SchemeId     string `protobuf:"bytes,1,opt,name=scheme_id,json=schemeId,proto3" json:"scheme_id,omitempty"`
}

func (x *NewsScheme) Reset() {
	*x = NewsScheme{}
	if protoimpl.UnsafeEnabled {
		mi := &file_newsletterpb_v1_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewsScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsScheme) ProtoMessage() {}

func (x *NewsScheme) ProtoReflect() protoreflect.Message {
	mi := &file_newsletterpb_v1_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsScheme.ProtoReflect.Descriptor instead.
func (*NewsScheme) Descriptor() ([]byte, []int) {
	return file_newsletterpb_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *NewsScheme) GetNewsLetterId() string {
	if x != nil {
		return x.NewsLetterId
	}
	return ""
}

func (x *NewsScheme) GetSchemeId() string {
	if x != nil {
		return x.SchemeId
	}
	return ""
}

var File_newsletterpb_v1_api_proto protoreflect.FileDescriptor

var file_newsletterpb_v1_api_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6e, 0x65, 0x77, 0x73, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6e, 0x65, 0x77,
	0x73, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x76, 0x31, 0x22, 0x43, 0x0a, 0x17,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x73, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0x5c, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x73, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12,
	0x24, 0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x73, 0x5f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x73, 0x4c, 0x65, 0x74,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22,
	0x4f, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x0e, 0x6e, 0x65, 0x77, 0x73, 0x5f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x65, 0x77, 0x73, 0x4c, 0x65, 0x74, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x49, 0x64,
	0x32, 0xbf, 0x01, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x73, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4e, 0x65, 0x77, 0x73, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x12, 0x28, 0x2e, 0x6e, 0x65, 0x77,
	0x73, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x73, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x6c, 0x65, 0x74, 0x74, 0x65,
	0x72, 0x70, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x73, 0x4c, 0x65, 0x74, 0x74, 0x65,
	0x72, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65,
	0x54, 0x6f, 0x4e, 0x65, 0x77, 0x73, 0x12, 0x1b, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x6c, 0x65, 0x74,
	0x74, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x73, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x65, 0x1a, 0x1b, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72,
	0x70, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x65, 0x77, 0x73, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65,
	0x22, 0x00, 0x42, 0x62, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x65, 0x77, 0x73, 0x6c, 0x65,
	0x74, 0x74, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x76, 0x31, 0x42, 0x08, 0x41, 0x70, 0x69, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x61, 0x6e, 0x6b, 0x65, 0x74, 0x68, 0x6b, 0x69, 0x6e, 0x69, 0x2f, 0x4e, 0x65,
	0x77, 0x73, 0x4c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x2d, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x77, 0x73, 0x6c, 0x65, 0x74, 0x74, 0x65,
	0x72, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_newsletterpb_v1_api_proto_rawDescOnce sync.Once
	file_newsletterpb_v1_api_proto_rawDescData = file_newsletterpb_v1_api_proto_rawDesc
)

func file_newsletterpb_v1_api_proto_rawDescGZIP() []byte {
	file_newsletterpb_v1_api_proto_rawDescOnce.Do(func() {
		file_newsletterpb_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_newsletterpb_v1_api_proto_rawDescData)
	})
	return file_newsletterpb_v1_api_proto_rawDescData
}

var file_newsletterpb_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_newsletterpb_v1_api_proto_goTypes = []interface{}{
	(*CreateNewsLetterRequest)(nil), // 0: newsletterpb.v1.CreateNewsLetterRequest
	(*NewsLetter)(nil),              // 1: newsletterpb.v1.NewsLetter
	(*NewsScheme)(nil),              // 2: newsletterpb.v1.NewsScheme
}
var file_newsletterpb_v1_api_proto_depIdxs = []int32{
	0, // 0: newsletterpb.v1.NewsLetterService.CreateNewsLetter:input_type -> newsletterpb.v1.CreateNewsLetterRequest
	2, // 1: newsletterpb.v1.NewsLetterService.AddSchemeToNews:input_type -> newsletterpb.v1.NewsScheme
	1, // 2: newsletterpb.v1.NewsLetterService.CreateNewsLetter:output_type -> newsletterpb.v1.NewsLetter
	2, // 3: newsletterpb.v1.NewsLetterService.AddSchemeToNews:output_type -> newsletterpb.v1.NewsScheme
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_newsletterpb_v1_api_proto_init() }
func file_newsletterpb_v1_api_proto_init() {
	if File_newsletterpb_v1_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_newsletterpb_v1_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNewsLetterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_newsletterpb_v1_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsLetter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_newsletterpb_v1_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewsScheme); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_newsletterpb_v1_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_newsletterpb_v1_api_proto_goTypes,
		DependencyIndexes: file_newsletterpb_v1_api_proto_depIdxs,
		MessageInfos:      file_newsletterpb_v1_api_proto_msgTypes,
	}.Build()
	File_newsletterpb_v1_api_proto = out.File
	file_newsletterpb_v1_api_proto_rawDesc = nil
	file_newsletterpb_v1_api_proto_goTypes = nil
	file_newsletterpb_v1_api_proto_depIdxs = nil
}
